<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run()
    {
        // Create a new user object
        $data = [
            [
                'id' => 'a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
                'first_name' => 'Admin',
                'last_name' => 'Admin',
                'username' => 'administrator',
                'role_id' => 1,
                'employee_number' => 'ID10001',
                'email' => 'admin@example.com',
                'phone' => '081234567890',
                'password' => password_hash('admin123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 'b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e',
                'first_name' => 'John',
                'last_name' => 'Doe',
                'username' => 'johndoe',
                'role_id' => 2,
                'employee_number' => 'ID10002',
                'email' => 'johndoe@kewasnet.com',
                'phone' => '0712345678',
                'password' => password_hash('johndoe123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 'c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f',
                'first_name' => 'Miriam',
                'last_name' => 'Alison',
                'username' => 'miriamalison',
                'role_id' => 3,
                'employee_number' => 'ID10003',
                'email' => 'miriamkash@gmail.com',
                'phone' => '0722345678',
                'password' => password_hash('miriamalison123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 'f2f47e80-5d74-4e4d-a659-2cf0ec6dd0b0',
                'first_name' => 'John',
                'last_name' => 'Smith',
                'username' => 'johnsmith',
                'role_id' => 2,
                'employee_number' => 'ID10004',
                'email' => 'john.smith@example.com',
                'phone' => '081234567891',
                'password' => password_hash('user1123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '45c7279a-39d8-47a7-bd5f-314291768f3e',
                'first_name' => 'Emily',
                'last_name' => 'Johnson',
                'username' => 'emilyjohnson',
                'role_id' => 2,
                'employee_number' => 'ID10005',
                'email' => 'emily.johnson@example.com',
                'phone' => '081234567892',
                'password' => password_hash('user2123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 'd948c387-d2bd-4406-a907-bbb4fc088dee',
                'first_name' => 'David',
                'last_name' => 'Williams',
                'username' => 'davidwilliams',
                'role_id' => 2,
                'employee_number' => 'ID10006',
                'email' => 'david.williams@example.com',
                'phone' => '081234567893',
                'password' => password_hash('user3123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '1c232bb0-8806-44fc-8f27-4de76a9494fd',
                'first_name' => 'Sarah',
                'last_name' => 'Brown',
                'username' => 'sarahbrown',
                'role_id' => 2,
                'employee_number' => 'ID10007',
                'email' => 'sarah.brown@example.com',
                'phone' => '081234567894',
                'password' => password_hash('user4123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '3f3a1dbd-682b-4825-8d51-27bda3a2e4b7',
                'first_name' => 'Michael',
                'last_name' => 'Davis',
                'username' => 'michaeldavis',
                'role_id' => 2,
                'employee_number' => 'ID10008',
                'email' => 'michael.davis@example.com',
                'phone' => '081234567895',
                'password' => password_hash('user5123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 'd247234b-e1c1-4073-b4de-e4e42133b66f',
                'first_name' => 'Jennifer',
                'last_name' => 'Martinez',
                'username' => 'jennifermartinez',
                'role_id' => 2,
                'employee_number' => 'ID10009',
                'email' => 'jennifer.martinez@example.com',
                'phone' => '081234567896',
                'password' => password_hash('user6123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '83346f47-b12b-46bd-a2a9-bf5736469afb',
                'first_name' => 'Daniel',
                'last_name' => 'Thompson',
                'username' => 'danielthompson',
                'role_id' => 2,
                'employee_number' => 'ID10010',
                'email' => 'daniel.thompson@example.com',
                'phone' => '081234567897',
                'password' => password_hash('user7123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 'c4614135-0c64-4ffe-8991-0d13034f4417',
                'first_name' => 'Laura',
                'last_name' => 'Clark',
                'username' => 'lauraclark',
                'role_id' => 2,
                'employee_number' => 'ID10011',
                'email' => 'laura.clark@example.com',
                'phone' => '081234567898',
                'password' => password_hash('user8123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '8c80eb40-0e6e-43f1-bf16-dd5e08b1651e',
                'first_name' => 'Matthew',
                'last_name' => 'Rodriguez',
                'username' => 'matthewrodriguez',
                'role_id' => 2,
                'employee_number' => 'ID10012',
                'email' => 'matthew.rodriguez@example.com',
                'phone' => '081234567899',
                'password' => password_hash('user9123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '9cb800c7-4bd2-40e7-be53-c2a7d591f58e',
                'first_name' => 'Jessica',
                'last_name' => 'Lee',
                'username' => 'jessicalee',
                'role_id' => 2,
                'employee_number' => 'ID10013',
                'email' => 'jessica.lee@example.com',
                'phone' => '081234567890',
                'password' => password_hash('user10123', PASSWORD_DEFAULT),
                'picture' => NULL,
                'bio' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.',
                'created_at' => date('Y-m-d H:i:s'),
                'email_verified_at' => date('Y-m-d H:i:s'),
            ]
        ];

        // Using Query Builder
        $users = model('App\Models\UserModel', false);

        $users->insertBatch($data);
    }
}
